name: Update Prices

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-market-prices
  cancel-in-progress: true

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کدها
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: نصب پایتون
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: نصب کتابخانه‌ها
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: اجرای اسکریپر
        run: python scraper.py

      - name: نمایش فایل قیمت‌ها
        run: cat data/prices.json

      - name: نمایش تغییرات قیمت
        run: git diff -- data/prices.json

      - name: ذخیره نتایج
        run: |
          git config user.name "MarketBot"
          git config user.email "bot@market.local"

          git add data/prices.json

          if git diff --cached --quiet; then
            echo "قیمت‌ها تغییری نکرده‌اند."
            exit 0
          fi

          git commit -m "بروزرسانی نرخ‌ها [skip ci]"
          git push
